# This is for Rocky Linux 9 with systemd installed
# and Core Development Tools installed:

# Group: Development Tools
# Description: A basic development environment.
# Mandatory Packages:
#   autoconf
#   automake
#   binutils
#   bison
#   flex
#   gcc
#   gcc-c++
#   gdb
#   glibc-devel
#   libtool
#   make
#   pkgconf
#   pkgconf-m4
#   pkgconf-pkg-config
#   redhat-rpm-config
#   rpm-build
#   rpm-sign
#   strace
# Default Packages:
#   asciidoc
#   byacc
#   diffstat
#   git
#   intltool
#   jna
#   ltrace
#   patchutils
#   perl-Fedora-VSP
#   perl-generators
#   pesign
#   source-highlight
#   systemtap
#   valgrind
#   valgrind-devel
# Optional Packages:
#   cmake
#   expect
#   rpmdevtools
#   rpmlint

FROM rockylinux:9
ENV container=docker

# Install systemd for rockylinux:minimal and clean unnecessary targets
RUN dnf -y install systemd; dnf clean all; \
(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN << EOF
dnf -y update && dnf clean all
dnf -y groupinstall "Development Tools"
dnf clean packages
EOF

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
